version: '3.5'

services:
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - db_volume:/data/db
  
  api:
    build: .
    ports:
      - 8000:8000

volumes:
  db_volume: